const videoGallery = [
  {
    title: "1 number (horror)",
    src: "./vids/p-21.mp4",
    poster: "./thumbnails/p-21.jpg",
  },
  {
    title: "2 number (horror)",
    src: "./vids/p-20.mp4",
    poster: "./thumbnails/p-20.jpg",
  },
  {
    title: "3 number (amalia devis)",
    src: "./vids/p-13.mp4",
    poster: "./thumbnails/p-13.jpg",
  },
  {
    title: "4 number",
    src: "./vids/p-7.mp4",
    poster: "./thumbnails/p-7.jpg",
  },
  {
    title: "5 number",
    src: "./vids/p-1.mp4",
    poster: "./thumbnails/p-1.jpg",
  },
  {
    title: "6 number",
    src: "./vids/p-6.mp4",
    poster: "./thumbnails/p-6.jpg",
  },
  {
    title: "7 number",
    src: "./vids/p-5.mp4",
    poster: "./thumbnails/p-5.jpg",
  },
];

export const driveData = [
  {
    kind: "drive#file",
    id: "1by42lsgg1SeByZoG7KBRygax7QrcBe81",
    name: "p-1.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1PsRVxMD69Gu7vOdvndn_dW6dOenZ__3q",
    name: "p-13.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "16yVqxTHWYtV27WxjduFwPBLzXldUOC9x",
    name: "p-7.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1ILq7BpjKHebaCuLlN1iT8Ms_cANHDsKG",
    name: "p-21.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1v1-FY5nk4RRrOFY8CrB5wtClDVzhdVXR",
    name: "p-32.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1Qw0SCHlYs3PH7Y0P5UuHtKl-e4AR1oYX",
    name: "p-20.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1RqIngZgLOHW96pvbLjBjEY3NoKS2Yzns",
    name: "p-28.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1LihHKYClyyMu2jGCXLHtBfaXqc_jWOmc",
    name: "p-29.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1oj1IrAE7mmnVB2HP6FSA9t7qObEpS02V",
    name: "p-34.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1LZMMuscPN8NRc5hcQzhIAuGG10APj6Al",
    name: "p-31.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1WNoN6YGgfhlKzUGfeAjQHn0cwhI7Qp1c",
    name: "p-27.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1oWbzUbYOq7UhkD34vUzAd3edyv8OwVdJ",
    name: "p-30.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1TGRJKcswohjMomaxsg-9AK_CRHaXYv8p",
    name: "p-26.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1G4O_M5uiOTJpwJ_XOrhcdSCshrYcB_sg",
    name: "p-12.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "10Tx9sIupvHjtImqniqSIVe3B5mxg6h6f",
    name: "p-25.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1R4HAwIhL2NYL6er9TEoyQXWIGawUPP9C",
    name: "p-22.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1kdHHJQ2TtUQ18MRp4Bw1BsOJgOnyPKMB",
    name: "p-23.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "19lb_pe2kDTOR-pQXxRxIsVCl4Yi56gaS",
    name: "p-24.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1AN1IiVFmf1PzsuN_ANt7GZJ8CMI1Volg",
    name: "p-18.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1NggF4u4HkrZvsSeUa4Ei1bTkyQTc9hRz",
    name: "p-19.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1bEiHngSzSw_V-_9D_l4WLsYKmrRkJDrN",
    name: "p-9.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1m22t2_G0qHE7dDjJ2VARUNx5RBKFhI3c",
    name: "p-8.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1S0RfC0_fEOblXXi--qPP2abBKD4B06Tg",
    name: "p-4.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1TGrQVb5Sa6Hkiz845h8V4WvjwdFZyZ6A",
    name: "p-5.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "15XHZAgkDnFcwT_tb6AKytvXZRpWZvTJE",
    name: "p-6.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1lBt5oZMvzAYlNi2wlyHeUUKBET5hsuHb",
    name: "p-3.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1SrJz5t9T927izH-41UqBenxeqAnsKc2h",
    name: "p-2.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1RZ6tvOwWSK8onIx4AeuBmAvFreNbGTij",
    name: "p-17.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "14kkm5r82oa5RnaN8Gjz_gnqjVTvxgO0Q",
    name: "p-14.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1VCKEEmPoaJVMVtpJkZSMHd-dzPs-9YiY",
    name: "p-16.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "166wZwY6xySkF4qZWYdXVr91QkIhO__hV",
    name: "p-11.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1J8JuuxjsLIWvTAmD0TgohTCYKl7raeRV",
    name: "p-15.mp4",
    mimeType: "video/mp4",
  },
  {
    kind: "drive#file",
    id: "1qxkGeCRbmBV3zH6mScKFplNFtqotYC7Q",
    name: "p-10.mp4",
    mimeType: "video/mp4",
  },
];
